### ISSUE TITLE
Separate Commands into Debug/Release

### ISSUE THREAD

**Issue by palechip** [HudPixel/HudPixel#6]
Some Commands are clearly only there for debug purpose while others offer actual functionality for the mod. In order not to confuse the users the mod shouldn't register debug commands when `HudPixelMod.IS_DEBUGGING` isn't active.
 
Tasks:
- [ ] Figure out which commands are debug commands.
- [ ] Prevent the debug commands from being registered when not debugging, i. e. making them invisible.
  - Maybe use `HpCommandBase`
- [ ] (Optional) Move some common code like `checkPermission()` to `HpCommandBase`
- [ ] Add a command to enable debug commands in release.

*Please don't do major refactoring because the commands are quite different in MC 1.8.9/1.11.2 and these changes would result in many merge conflicts.*

**Comment by Eladkay** [comment]
Debugging commands are used for debugging in release too and I frequently ask users who have problems with game detection to give me output of debug commands.

**Comment by palechip** [comment]
Got a point. Added an extra task:
> Add a command to enable debug commands in release.

**Comment by Eladkay** [comment]
That’s silly. They’re not visible in /help or elsewhere as is.

**Comment by palechip** [comment]
Agreed. There probably isn't any change necessary now.
